<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.8.6 on darwin)" generated="20210217 21:51:58.564" rpa="false">
<suite id="s1" name="Rwa Api Smoke" source="/Users/davidkrist/PycharmProjects/course-robot-framework-python-rwa/api/testsuites/rwa/tests/rwa_api_smoke.robot">
<kw name="Setup" library="SuiteSetup" type="setup">
<doc>KW prihlasi uzivatele do aplikace rwa.</doc>
<msg timestamp="20210217 21:51:58.763" level="WARN">Connection error, viz vyjimka: (MaxRetryError("HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /login (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106b3d640&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))"),)</msg>
<msg timestamp="20210217 21:51:58.767" level="FAIL">ConnectionError: HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /login (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106b3d640&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<status status="FAIL" starttime="20210217 21:51:58.749" endtime="20210217 21:51:58.768"></status>
</kw>
<test id="s1-t1" name="Get bank account">
<doc>Test overi spravnost detailu vychoziho bankovniho uctu prihlaseneho uzivatele.</doc>
<tags>
<tag>check_bank_acc</tag>
<tag>smoke</tag>
</tags>
<status status="FAIL" starttime="20210217 21:51:58.769" endtime="20210217 21:51:58.772" critical="yes">Parent suite setup failed:
ConnectionError: HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /login (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106b3d640&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</test>
<test id="s1-t2" name="Get notifications">
<doc>Test vrati seznam vsech notifikaci prihlaseneho uzivatele.</doc>
<tags>
<tag>get_notif</tag>
<tag>smoke</tag>
</tags>
<status status="FAIL" starttime="20210217 21:51:58.773" endtime="20210217 21:51:58.774" critical="yes">Parent suite setup failed:
ConnectionError: HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /login (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106b3d640&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</test>
<test id="s1-t3" name="Delete n notifications">
<doc>Test smaze n anebo vsechny notifikace prihlaseneho uzivatele podle vybraneho jmena v notifikaci.</doc>
<tags>
<tag>del_notif</tag>
<tag>smoke</tag>
</tags>
<status status="FAIL" starttime="20210217 21:51:58.774" endtime="20210217 21:51:58.777" critical="yes">Parent suite setup failed:
ConnectionError: HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /login (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106b3d640&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</test>
<test id="s1-t4" name="Send money">
<doc>Test odesle platbu vybranemu prijemci ze seznamu pratel.</doc>
<tags>
<tag>send_money</tag>
<tag>smoke</tag>
</tags>
<status status="FAIL" starttime="20210217 21:51:58.779" endtime="20210217 21:51:58.780" critical="yes">Parent suite setup failed:
ConnectionError: HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /login (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106b3d640&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</test>
<kw name="Teardown" library="SuiteTeardown" type="teardown">
<doc>KW odhlasi prihlaseneho uzivatele z aplikace rwa a ukonci aktivni session.</doc>
<msg timestamp="20210217 21:51:58.786" level="WARN">Connection error, viz vyjimka: (MaxRetryError("HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /logout (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106c19ac0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))"),)</msg>
<msg timestamp="20210217 21:51:58.790" level="FAIL">ConnectionError: HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /logout (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106c19ac0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<status status="FAIL" starttime="20210217 21:51:58.781" endtime="20210217 21:51:58.790">ConnectionError: HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /logout (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106c19ac0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<doc>Testovaci sada obsahuje vybrane testy pro validaci rwa api. Pro prihlaseni do api se pouziva
uzivatel: Katharina_Bernier.</doc>
<status status="FAIL" starttime="20210217 21:51:58.566" endtime="20210217 21:51:58.791">Suite setup failed:
ConnectionError: HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /login (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106b3d640&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

Also suite teardown failed:
ConnectionError: HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /logout (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106c19ac0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</suite>
<statistics>
<total>
<stat pass="0" fail="4">Critical Tests</stat>
<stat pass="0" fail="4">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1">check_bank_acc</stat>
<stat pass="0" fail="1">del_notif</stat>
<stat pass="0" fail="1">get_notif</stat>
<stat pass="0" fail="1">send_money</stat>
<stat pass="0" fail="4">smoke</stat>
</tag>
<suite>
<stat pass="0" fail="4" id="s1" name="Rwa Api Smoke">Rwa Api Smoke</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210217 21:51:58.600" level="WARN">Imported library '/Users/davidkrist/PycharmProjects/course-robot-framework-python-rwa/_common' contains no keywords.</msg>
<msg timestamp="20210217 21:51:58.763" level="WARN">Connection error, viz vyjimka: (MaxRetryError("HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /login (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106b3d640&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))"),)</msg>
<msg timestamp="20210217 21:51:58.786" level="WARN">Connection error, viz vyjimka: (MaxRetryError("HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /logout (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106c19ac0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))"),)</msg>
</errors>
</robot>
